### ISSUE TITLE
Add-in Can't Find Tags for v12

### ISSUE THREAD

**Issue by txchemd1627** [Osborw/uworld-batch-unsuspend#1]
If I read through the code right, it looks like this is searching for the step deck v11 tags. Is there a way to have it also search v12 or is there another way I should be doing this?

**Comment by Osborw** [comment]
You're right, at the moment this only looks at Step1 v11.

I've wanted to make this more flexible actually since students are beginning to look at Step 2 cards as well.

I'm going to be taking a look into this over the next week. I'll post some updates as I go

**Comment by Osborw** [comment]
@txchemd1627  I should be able to add this option without too much issue, but I don't have the cards personally myself to test.

Are the cards structured similarly to v11? By that, I mean that the tags organize the cards in specific ways by number. See the example below:

![Anki_Uworld_Structure](https://github.com/Osborw/uworld-batch-unsuspend/assets/32249906/cdf72bbb-ca7a-4270-98b1-99b9e1e323f7)

Let me know if this is accurate. A screenshot would be helpful. If it is, then I can go ahead and make the change

**Comment by txchemd1627** [comment]
@Osborw Yes they appear the same as v11, screenshots below. A specific tag example for UWorld QID 14877 is also below. Thanks so much for looking into this
<img width="133" alt="image" src="https://github.com/Osborw/uworld-batch-unsuspend/assets/172729056/cd4e7122-63f5-4583-a47c-f5018b2cdf15">

![image](https://github.com/Osborw/uworld-batch-unsuspend/assets/172729056/1de8f54e-62c4-4a2c-9ac2-250632542c24)

**Comment by Osborw** [comment]
@txchemd1627 thanks for the screenshots, that's perfect!

Just merged in a [new PR](https://github.com/Osborw/uworld-batch-unsuspend/pull/3) that adds this functionality for v12 cards for Step 1 and Step 2.

I've also updated the Add-on on the [Anki website](https://ankiweb.net/shared/info/899971795), so feel free to update and try it out.

Since I don't have the v12 deck, let me know if you run into any issues. Or if there are some cards it can't find, send screenshots here like you did before, and I can put in a fix :)

**Comment by txchemd1627** [comment]
It worked, thanks so much!

**Comment by Osborw** [comment]
You're welcome! I'll keep this Issue open for a few more days in case you run into any issues
